# Generated by Django 5.2.6 on 2025-09-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotamensual',
            name='mes_año',
            field=models.CharField(max_length=7),
        ),
    ]
