# Generated by Django 5.2.6 on 2025-09-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_cuotamensual_mes_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaunidad',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID del pago en la pasarela', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuotaunidad',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Método de pago usado', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuotaunidad',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Referencia del pago', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuotaunidad',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', help_text='Estado del pago en la pasarela', max_length=20),
        ),
        migrations.AddField(
            model_name='cuotaunidad',
            name='payment_url',
            field=models.URLField(blank=True, help_text='URL de pago generada por la pasarela', null=True),
        ),
        migrations.AlterField(
            model_name='cuotaunidad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('parcial', 'Pago Parcial'), ('procesando', 'Procesando Pago'), ('fallido', 'Pago Fallido')], default='pendiente', max_length=20),
        ),
    ]
