# Generated by Django 5.2.6 on 2025-09-29 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0010_add_destinatarios_field'),
        ('finanzas', '0003_cuotaunidad_payment_id_cuotaunidad_payment_method_and_more'),
        ('usuarios', '0008_configuracionacceso_placainvitado_placavehiculo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_ingreso', models.CharField(choices=[('cuotas', 'Cuotas Mensuales'), ('multas', 'Multas'), ('servicios', 'Servicios Adicionales'), ('alquiler', 'Alquiler de Áreas Comunes'), ('eventos', 'Eventos'), ('donaciones', 'Donaciones'), ('otros', 'Otros Ingresos')], max_length=20)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_ingresos/')),
                ('numero_referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('cuota_relacionada', models.ForeignKey(blank=True, help_text='Cuota relacionada con el ingreso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cuotaunidad')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('residente_relacionado', models.ForeignKey(blank=True, help_text='Residente relacionado con el ingreso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.persona')),
                ('unidad_relacionada', models.ForeignKey(blank=True, help_text='Unidad relacionada con el ingreso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comunidad.unidad')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha_ingreso', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ResumenIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_año', models.CharField(max_length=7)),
                ('total_cuotas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_multas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_alquiler', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_eventos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_donaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_otros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_general', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumen de Ingresos',
                'verbose_name_plural': 'Resúmenes de Ingresos',
                'ordering': ['-mes_año'],
                'unique_together': {('mes_año',)},
            },
        ),
    ]
