# Generated by Django 5.2.6 on 2025-09-27 14:33

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0008_reglamento_alter_notificacion_options_and_more'),
        ('economia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multa',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Multa', 'verbose_name_plural': 'Multas'},
        ),
        migrations.RenameField(
            model_name='multa',
            old_name='fecha',
            new_name='fecha_emision',
        ),
        migrations.AddField(
            model_name='multa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='multa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multa',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2025, 9, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multa',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='reglamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidad.reglamento'),
        ),
    ]
