# Generated by Django 5.2.6 on 2025-09-29 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0002_alter_multa_options_rename_fecha_multa_fecha_emision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorFinanciero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_indicador', models.CharField(choices=[('liquidez', 'Liquidez'), ('solvencia', 'Solvencia'), ('rentabilidad', 'Rentabilidad'), ('eficiencia', 'Eficiencia'), ('morosidad', 'Morosidad')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unidad', models.CharField(default='%', max_length=20)),
                ('fecha_calculo', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('formula', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Indicador Financiero',
                'verbose_name_plural': 'Indicadores Financieros',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='AnalisisFinanciero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_analisis', models.CharField(choices=[('tendencia', 'Análisis de Tendencia'), ('comparativo', 'Análisis Comparativo'), ('proyeccion', 'Proyección Financiera'), ('eficiencia', 'Análisis de Eficiencia'), ('morosidad', 'Análisis de Morosidad')], max_length=20)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('datos_analisis', models.JSONField(default=dict)),
                ('conclusiones', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis Financiero',
                'verbose_name_plural': 'Análisis Financieros',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DashboardFinanciero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('widgets_config', models.JSONField(default=list)),
                ('filtros_default', models.JSONField(default=dict)),
                ('es_publico', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Financiero',
                'verbose_name_plural': 'Dashboards Financieros',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteFinanciero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_reporte', models.CharField(choices=[('mensual', 'Reporte Mensual'), ('trimestral', 'Reporte Trimestral'), ('anual', 'Reporte Anual'), ('personalizado', 'Reporte Personalizado')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], default='generando', max_length=20)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_multas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_neto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Financiero',
                'verbose_name_plural': 'Reportes Financieros',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
