# Generated by Django 5.2.6 on 2025-09-21 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_vehiculo_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentes',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
