# Generated by Django 5.2.6 on 2025-09-21 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentes',
            name='usuario_asociado',
            field=models.ForeignKey(blank=True, help_text='Usuario residente principal asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes_asociados', to=settings.AUTH_USER_MODEL),
        ),
    ]
