# Generated by Django 5.2.6 on 2025-09-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_residentes_usuario_asociado'),
    ]

    operations = [
    ]
