# Generated by Django 5.2.6 on 2025-09-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20250921_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
