# Generated by Django 5.2.6 on 2025-09-24 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_persona_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAcceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio_restringida', models.TimeField(blank=True, help_text='Hora de inicio de restricción', null=True)),
                ('hora_fin_restringida', models.TimeField(blank=True, help_text='Hora de fin de restricción', null=True)),
                ('umbral_confianza_placa', models.DecimalField(decimal_places=2, default=80.0, help_text='Umbral mínimo de confianza para placa (0-100)', max_digits=5)),
                ('umbral_confianza_vehiculo', models.DecimalField(decimal_places=2, default=70.0, help_text='Umbral mínimo de confianza para vehículo (0-100)', max_digits=5)),
                ('tiempo_max_procesamiento', models.DecimalField(decimal_places=2, default=30.0, help_text='Tiempo máximo de procesamiento en segundos', max_digits=6)),
                ('notificar_accesos_denegados', models.BooleanField(default=True)),
                ('notificar_accesos_no_reconocidos', models.BooleanField(default=True)),
                ('notificar_mantenimiento', models.BooleanField(default=True)),
                ('camaras_activas', models.IntegerField(default=1, help_text='Número de cámaras activas')),
                ('fps_captura', models.IntegerField(default=15, help_text='Frames por segundo para captura')),
                ('dias_retencion_imagenes', models.IntegerField(default=30, help_text='Días para retener imágenes')),
                ('dias_retencion_registros', models.IntegerField(default=90, help_text='Días para retener registros de acceso')),
            ],
        ),
        migrations.CreateModel(
            name='PlacaInvitado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_visitante', models.CharField(blank=True, max_length=100, null=True)),
                ('ci_visitante', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_autorizacion', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placas_invitado', to='usuarios.residentes')),
            ],
        ),
        migrations.CreateModel(
            name='PlacaVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placas_vehiculo', to='usuarios.residentes')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa_detectada', models.CharField(max_length=10)),
                ('marca_detectada', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_detectado', models.CharField(blank=True, max_length=50, null=True)),
                ('color_detectado', models.CharField(blank=True, max_length=30, null=True)),
                ('ia_confidence', models.DecimalField(decimal_places=2, help_text='Confianza de la IA (0-100)', max_digits=5)),
                ('ia_autentico', models.BooleanField(default=False, help_text='¿La IA confirmó que es auténtico?')),
                ('ia_placa_reconocida', models.BooleanField(default=False, help_text='¿La IA reconoció la placa?')),
                ('ia_vehiculo_reconocido', models.BooleanField(default=False, help_text='¿La IA reconoció el vehículo?')),
                ('tipo_acceso', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('estado_acceso', models.CharField(choices=[('autorizado', 'Autorizado'), ('denegado', 'Denegado'), ('pendiente', 'Pendiente de Autorización'), ('error_ia', 'Error en IA')], default='pendiente', max_length=20)),
                ('imagen_url', models.TextField(blank=True, help_text='URL de la imagen capturada', null=True)),
                ('imagen_path', models.TextField(blank=True, help_text='Path local de la imagen', null=True)),
                ('camara_id', models.CharField(blank=True, help_text='ID de la cámara que capturó', max_length=50, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tiempo_procesamiento', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo en segundos que tomó procesar', max_digits=6, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, help_text='Usuario que autorizó manualmente', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('placa_invitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.placainvitado')),
                ('placa_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.placavehiculo')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
