# Generated by Django 5.2.6 on 2025-09-29 03:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_configuracionacceso_placainvitado_placavehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('limpieza', 'Limpieza'), ('seguridad', 'Seguridad'), ('administrativo', 'Administrativo'), ('jardineria', 'Jardinería'), ('piscina', 'Piscina'), ('gimnasio', 'Gimnasio'), ('salon_eventos', 'Salón de Eventos'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad_default', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('duracion_estimada_horas', models.IntegerField(default=1, help_text='Duración estimada en horas')),
                ('requiere_especialista', models.BooleanField(default=False)),
                ('requiere_herramientas', models.BooleanField(default=False)),
                ('materiales_necesarios', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tarea',
                'verbose_name_plural': 'Tipos de Tareas',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TareaEmpleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada'), ('rechazada', 'Rechazada')], default='asignada', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('materiales_proporcionados', models.TextField(blank=True)),
                ('herramientas_necesarias', models.TextField(blank=True)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('progreso_porcentaje', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observaciones_empleado', models.TextField(blank=True)),
                ('observaciones_supervisor', models.TextField(blank=True)),
                ('foto_antes', models.ImageField(blank=True, null=True, upload_to='tareas/fotos/')),
                ('foto_despues', models.ImageField(blank=True, null=True, upload_to='tareas/fotos/')),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='tareas/documentos/')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('empleado_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='usuarios.empleado')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_supervisadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipotarea')),
            ],
            options={
                'verbose_name': 'Tarea de Empleado',
                'verbose_name_plural': 'Tareas de Empleados',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calidad_trabajo', models.IntegerField(choices=[(1, 'Muy Malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')])),
                ('cumplimiento_tiempo', models.IntegerField(choices=[(1, 'Muy Malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')])),
                ('uso_recursos', models.IntegerField(choices=[(1, 'Muy Malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')])),
                ('comunicacion', models.IntegerField(choices=[(1, 'Muy Malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')])),
                ('comentarios_positivos', models.TextField(blank=True)),
                ('areas_mejora', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='usuarios.tareaempleado')),
            ],
            options={
                'verbose_name': 'Evaluación de Tarea',
                'verbose_name_plural': 'Evaluaciones de Tareas',
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('es_interno', models.BooleanField(default=False, help_text='Si es True, solo lo ve el supervisor')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.tareaempleado')),
            ],
            options={
                'verbose_name': 'Comentario de Tarea',
                'verbose_name_plural': 'Comentarios de Tareas',
                'ordering': ['-fecha_comentario'],
            },
        ),
    ]
