# Generated by Django 5.2.6 on 2025-09-29 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_update_invitado_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='tipo',
            field=models.CharField(choices=[('casual', 'Visita Casual'), ('evento', 'Invitado Evento')], default='casual', max_length=10),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
