# Generated by Django 5.2.6 on 2025-09-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_mantenimiento_bitacoramantenimiento_reglamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('area', 'fecha', 'hora_inicio')},
        ),
    ]
