# Generated by Django 5.2.6 on 2025-09-29 03:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_reserva_costo_reserva_motivo_reserva_pagado_and_more'),
        ('usuarios', '0008_configuracionacceso_placainvitado_placavehiculo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('emergencia', 'Mantenimiento de Emergencia'), ('limpieza', 'Limpieza y Aseo'), ('reparacion', 'Reparación'), ('renovacion', 'Renovación'), ('inspeccion', 'Inspección')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad_default', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('frecuencia_dias', models.IntegerField(default=30, help_text='Frecuencia en días para mantenimiento preventivo')),
                ('duracion_estimada_horas', models.IntegerField(default=2, help_text='Duración estimada en horas')),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requiere_especialista', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='bitacoramantenimiento',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Bitácora de Mantenimiento', 'verbose_name_plural': 'Bitácoras de Mantenimiento'},
        ),
        migrations.RemoveField(
            model_name='bitacoramantenimiento',
            name='avance',
        ),
        migrations.RemoveField(
            model_name='bitacoramantenimiento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='bitacoramantenimiento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='bitacoramantenimiento',
            name='mantenimiento',
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='mantenimiento/documentos/'),
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='mantenimiento/fotos/'),
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='mantenimiento/fotos/'),
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='horas_trabajadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='materiales_usados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='tipo_actividad',
            field=models.CharField(choices=[('inicio', 'Inicio de Trabajo'), ('progreso', 'Progreso'), ('completado', 'Trabajo Completado'), ('problema', 'Problema Encontrado'), ('solucion', 'Solución Aplicada'), ('observacion', 'Observación'), ('material', 'Uso de Material'), ('pausa', 'Pausa en Trabajo')], default='observacion', max_length=20),
        ),
        migrations.CreateModel(
            name='BitacoraMantenimientoAntigua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avance', models.TextField()),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('costo_adquisicion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_actual', models.CharField(choices=[('bueno', 'Buen Estado'), ('regular', 'Estado Regular'), ('malo', 'Mal Estado'), ('fuera_servicio', 'Fuera de Servicio'), ('reparacion', 'En Reparación')], default='bueno', max_length=20)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('frecuencia_mantenimiento_dias', models.IntegerField(default=90)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='mantenimiento.areacomun')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario de Área',
                'verbose_name_plural': 'Inventario de Áreas',
                'ordering': ['area_comun', 'nombre_equipo'],
            },
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('costo_presupuestado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('materiales_necesarios', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='mantenimiento.areacomun')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipomantenimiento')),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='plan_mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='mantenimiento.planmantenimiento'),
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('materiales_utilizados', models.TextField(blank=True)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado')),
                ('plan_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='mantenimiento.planmantenimiento')),
            ],
            options={
                'verbose_name': 'Tarea de Mantenimiento',
                'verbose_name_plural': 'Tareas de Mantenimiento',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='mantenimiento.tareamantenimiento'),
        ),
    ]
