# Generated by Django 5.2.6 on 2025-10-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_tipomantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='vista_por_admin',
            field=models.BooleanField(default=False),
        ),
    ]
