# Generated by Django 5.2.6 on 2025-09-20 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_casa', models.CharField(max_length=10)),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_residentes', models.IntegerField()),
                ('cantidad_mascotas', models.IntegerField()),
                ('cantidad_vehiculos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.residentes')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionResidente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leido', models.BooleanField(default=False)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.notificacion')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.residentes')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentesUnidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.residentes')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.unidad')),
            ],
        ),
    ]
