# Generated by Django 5.2.6 on 2025-09-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
        ('usuarios', '0003_residentes_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentesunidad',
            name='rol_en_unidad',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino'), ('familiar', 'Familiar')], default='propietario', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='residentesunidad',
            unique_together={('id_residente', 'id_unidad', 'fecha_inicio')},
        ),
    ]
