# Generated by Django 5.2.6 on 2025-09-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_residentesunidad_rol_en_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentesunidad',
            name='rol_en_unidad',
            field=models.CharField(choices=[('residente', 'Residente'), ('inquilino', 'Inquilino'), ('propietario', 'Propietario'), ('familiar', 'Familiar')], default='residente', max_length=20),
        ),
    ]
