# Generated by Django 5.2.6 on 2025-09-25 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_alter_residentesunidad_rol_en_unidad'),
        ('usuarios', '0008_configuracionacceso_placainvitado_placavehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('pez', 'Pez'), ('otro', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='usuarios.residentes')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidad.unidad')),
            ],
        ),
    ]
