# Generated by Django 5.2.6 on 2025-09-26 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_mascota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['numero_casa'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AddField(
            model_name='unidad',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la unidad está activa'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidad',
            name='cantidad_mascotas',
            field=models.IntegerField(default=0, help_text='Número de mascotas registradas'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='cantidad_residentes',
            field=models.IntegerField(default=0, help_text='Número de residentes actuales'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='cantidad_vehiculos',
            field=models.IntegerField(default=0, help_text='Número de vehículos registrados'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='metros_cuadrados',
            field=models.DecimalField(decimal_places=2, help_text='Área en metros cuadrados', max_digits=10),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='numero_casa',
            field=models.CharField(help_text='Número único de la unidad (ej: A-101, B-205)', max_length=10, unique=True),
        ),
    ]
