# Generated by Django 5.2.6 on 2025-09-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0005_alter_unidad_options_unidad_activa_and_more'),
        ('mantenimiento', '0003_reserva_costo_reserva_motivo_reserva_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.areacomun'),
        ),
    ]
