# Generated by Django 5.2.6 on 2025-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0006_evento_area'),
        ('mantenimiento', '0003_reserva_costo_reserva_motivo_reserva_pagado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='area',
        ),
        migrations.AddField(
            model_name='evento',
            name='areas',
            field=models.ManyToManyField(blank=True, to='mantenimiento.areacomun'),
        ),
    ]
