# Generated by Django 5.2.6 on 2025-09-27 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0007_remove_evento_area_evento_areas'),
        ('usuarios', '0008_configuracionacceso_placainvitado_placavehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articulo', models.CharField(max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('general', 'General'), ('multa', 'Multa'), ('sancion', 'Sanción'), ('cuota', 'Cuota'), ('mantenimiento', 'Mantenimiento'), ('convivencia', 'Convivencia')], max_length=20)),
                ('monto_multa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dias_suspension', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reglamento',
                'verbose_name_plural': 'Reglamentos',
                'ordering': ['articulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='notificacionresidente',
            options={'verbose_name': 'Notificación por Residente', 'verbose_name_plural': 'Notificaciones por Residente'},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='enviar_a_todos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacionresidente',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cuota', 'Cuota'), ('multa', 'Multa'), ('comunicado', 'Comunicado'), ('evento', 'Evento'), ('mantenimiento', 'Mantenimiento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='notificacionresidente',
            unique_together={('notificacion', 'residente')},
        ),
    ]
