# Generated by Django 5.2.6 on 2025-09-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0008_reglamento_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentesunidad',
            name='rol_en_unidad',
            field=models.CharField(choices=[('residente', 'Residente'), ('inquilino', 'Inquilino'), ('propietario', 'Propietario')], default='residente', max_length=20),
        ),
    ]
