# Generated by Django 5.2.6 on 2025-09-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0009_remove_familiar_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='destinatarios',
            field=models.JSONField(blank=True, default=dict, help_text='Destinatarios específicos: {residentes: true, empleados: false, seguridad: true}'),
        ),
    ]
