# Generated by Django 5.2.6 on 2025-10-01 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0010_add_destinatarios_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaComunicado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(help_text='Rol del usuario al momento de la lectura', max_length=50)),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura de Comunicado',
                'verbose_name_plural': 'Lecturas de Comunicados',
                'ordering': ['-fecha_lectura'],
                'unique_together': {('notificacion', 'usuario')},
            },
        ),
    ]
