# Generated by Django 5.2.6 on 2025-10-01 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0012_areacomun_alter_evento_areas_reserva'),
        ('mantenimiento', '0004_tipomantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_comunidad', to='mantenimiento.areacomun'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='areas',
            field=models.ManyToManyField(blank=True, to='mantenimiento.areacomun'),
        ),
        migrations.DeleteModel(
            name='AreaComun',
        ),
    ]
